insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anestassia Henrie', 'Larry', '1990-12-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harris Magill', 'Maywood', '2000-09-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Peyter Maffiotti', 'Doe Crossing', '1986-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ursala Deluca', 'Hintze', '1980-01-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Othella Bulter', 'Grasskamp', '1998-09-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adelind Bradley', 'Crest Line', '1971-09-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sidoney Kilshall', 'Michigan', '1992-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Melany Hempel', 'Hallows', '1952-05-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elsey Siege', 'Dottie', '1954-08-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlene Marran', 'Lakewood', '2002-11-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Othella Prothero', 'Sundown', '2011-07-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nickie Farens', 'Stoughton', '2002-08-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bern Anselmi', 'Westend', '1993-04-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lucienne De Meis', 'Washington', '1983-06-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thorstein Fronks', 'Pankratz', '2006-04-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Samson Saddler', 'Colorado', '1969-09-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christel Diviny', 'Wayridge', '2007-01-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maxy Dosdale', 'Arapahoe', '1969-10-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liuka Houltham', 'Dapin', '1982-01-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kalil Petlyura', 'Mayer', '1980-02-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Julian Fidelli', 'Pine View', '1956-09-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Loree Buxey', 'Bashford', '1956-06-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lulita Donke', 'Lawn', '2014-02-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kennie Hercules', 'Boyd', '1973-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Selestina Shercliff', 'Elmside', '1959-12-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Paige Gladdolph', 'Sheridan', '1966-09-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Seana MacCheyne', 'Esker', '2009-08-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angelle Wauchope', 'Park Meadow', '1996-07-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rudie Jedrzejczyk', 'Amoth', '1990-05-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ludvig McMenamy', 'Meadow Valley', '1989-06-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karlene Pickin', 'Lyons', '1954-11-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Theodore Cosyns', 'Corry', '1984-08-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Krispin Lawford', 'Clyde Gallagher', '2009-11-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kathryn Eagar', 'Crest Line', '1954-10-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sawyer Lagadu', 'Thompson', '1952-06-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gunter Maunton', 'Montana', '2003-04-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Merilyn Cattermoul', 'Algoma', '1966-07-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cyrille Wetherell', 'Utah', '2013-06-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Delainey Rands', 'Helena', '1979-09-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leonhard Whinray', 'Towne', '1971-01-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dell Symmers', 'Ruskin', '2015-12-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dasya Jakubovski', 'Manitowish', '1966-10-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Friederike Wike', 'Ridgeway', '1965-06-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ogdon Darragh', 'Lakewood Gardens', '2008-05-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thia Cobby', 'Lake View', '1989-07-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Portia Hewkin', 'Corry', '1966-09-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Olav Ucceli', 'Chive', '1990-01-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shayne Losseljong', 'Carberry', '1985-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alexis Sturley', 'Judy', '1998-09-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nicki Longfield', 'Buena Vista', '1972-06-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('De Derle', 'Vernon', '1986-03-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Luther Hardiman', 'Sherman', '1962-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marion Dumberell', 'Tennessee', '2014-09-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maddi Dawidowsky', 'Forster', '2013-11-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marisa Rapelli', 'Golf Course', '1955-10-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emili Dysert', 'Pearson', '1967-10-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raimondo Pach', 'Calypso', '1998-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bartlett Ryrie', 'Bobwhite', '2013-10-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gilly Lomasney', 'Algoma', '1966-06-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rhys Dufore', 'Melrose', '1988-10-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeromy Philler', 'South', '1970-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Demott Dondon', 'Maple Wood', '1984-03-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tessa Crosen', 'Continental', '2009-09-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Samuel Laxtonne', 'Schmedeman', '1950-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bel Valintine', 'Buell', '1959-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Paule Moggle', 'Mcbride', '1987-04-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fan Sympson', 'Carioca', '2010-07-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Debra Sloegrave', 'Anthes', '1955-02-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karlotte Aleksandrev', 'Mockingbird', '2009-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jereme Planke', 'Manufacturers', '2012-01-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mozelle Emer', 'Elmside', '1977-08-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tate Cammell', 'Victoria', '1986-03-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Calhoun Baugh', 'Nobel', '2005-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Reena Farnish', 'Shelley', '1991-08-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlowe Learmont', 'Crescent Oaks', '1964-04-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marillin Saffran', 'Jana', '1992-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vassily Schwandt', 'Loeprich', '1985-12-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danie Knutton', 'Kropf', '1995-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Philippe Kendall', 'Hagan', '1993-09-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Torrie Crocetti', 'Harbort', '1958-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Toby Matcham', 'Weeping Birch', '1991-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jere Camber', 'Green Ridge', '1957-11-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Calla Grebner', 'Mcguire', '2010-06-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fidela Withams', 'Vidon', '1990-03-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Avigdor Orrill', 'Valley Edge', '1958-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bailey Gladebeck', 'Lighthouse Bay', '1984-01-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karel Phythian', 'Welch', '1968-10-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Worden Niles', 'Lukken', '1997-09-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maxy Whale', 'Manitowish', '2002-08-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jillene Gulliford', 'Lindbergh', '2017-08-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Merv Simoneau', 'Butterfield', '2011-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emelen Hagerty', '7th', '2007-04-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hasty Kings', 'Sullivan', '1964-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mag MacGille', 'Artisan', '2013-10-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kathleen Glentz', 'Golf', '2011-05-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Noach Gherarducci', 'Morrow', '1978-10-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Devlen Schurig', 'Manufacturers', '2002-05-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Roselia Philippeaux', 'Summerview', '1981-03-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bronny Annetts', 'Clemons', '2004-11-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rodi Andor', 'Pond', '1986-08-02');
