insert into tren (modelo, capacidad) values ('Sportvan G20', 1);
insert into tren (modelo, capacidad) values ('Pilot', 2);
insert into tren (modelo, capacidad) values ('3 Series', 3);
insert into tren (modelo, capacidad) values ('Stratus', 4);
insert into tren (modelo, capacidad) values ('E150', 5);
insert into tren (modelo, capacidad) values ('Prizm', 6);
insert into tren (modelo, capacidad) values ('G-Series G10', 7);
insert into tren (modelo, capacidad) values ('Truck', 8);
insert into tren (modelo, capacidad) values ('Tacoma', 9);
insert into tren (modelo, capacidad) values ('Astra', 10);
insert into tren (modelo, capacidad) values ('V40', 11);
insert into tren (modelo, capacidad) values ('Esprit', 12);
insert into tren (modelo, capacidad) values ('NSX', 13);
insert into tren (modelo, capacidad) values ('Ram 1500 Club', 14);
insert into tren (modelo, capacidad) values ('Justy', 15);
insert into tren (modelo, capacidad) values ('Prowler', 16);
insert into tren (modelo, capacidad) values ('Legacy', 17);
insert into tren (modelo, capacidad) values ('GL-Class', 18);
insert into tren (modelo, capacidad) values ('Safari', 19);
insert into tren (modelo, capacidad) values ('240SX', 20);
insert into tren (modelo, capacidad) values ('A4', 21);
insert into tren (modelo, capacidad) values ('Hombre', 22);
insert into tren (modelo, capacidad) values ('QX', 23);
insert into tren (modelo, capacidad) values ('S2000', 24);
insert into tren (modelo, capacidad) values ('del Sol', 25);
insert into tren (modelo, capacidad) values ('Cobalt', 26);
insert into tren (modelo, capacidad) values ('Venture', 27);
insert into tren (modelo, capacidad) values ('Laser', 28);
insert into tren (modelo, capacidad) values ('Vantage', 29);
insert into tren (modelo, capacidad) values ('Ram 3500 Club', 30);
insert into tren (modelo, capacidad) values ('5 Series', 31);
insert into tren (modelo, capacidad) values ('ES', 32);
insert into tren (modelo, capacidad) values ('Escort', 33);
insert into tren (modelo, capacidad) values ('Accord', 34);
insert into tren (modelo, capacidad) values ('S4', 35);
insert into tren (modelo, capacidad) values ('Grand Marquis', 36);
insert into tren (modelo, capacidad) values ('A8', 37);
insert into tren (modelo, capacidad) values ('Aurora', 38);
insert into tren (modelo, capacidad) values ('C-Class', 39);
insert into tren (modelo, capacidad) values ('Murano', 40);
insert into tren (modelo, capacidad) values ('Focus', 41);
insert into tren (modelo, capacidad) values ('Esperante', 42);
insert into tren (modelo, capacidad) values ('Caliber', 43);
insert into tren (modelo, capacidad) values ('LTD Crown Victoria', 44);
insert into tren (modelo, capacidad) values ('Corvette', 45);
insert into tren (modelo, capacidad) values ('Neon', 46);
insert into tren (modelo, capacidad) values ('Classic', 47);
insert into tren (modelo, capacidad) values ('Park Avenue', 48);
insert into tren (modelo, capacidad) values ('Focus', 49);
insert into tren (modelo, capacidad) values ('Impala', 50);
insert into tren (modelo, capacidad) values ('Alcyone SVX', 51);
insert into tren (modelo, capacidad) values ('Justy', 52);
insert into tren (modelo, capacidad) values ('L-Series', 53);
insert into tren (modelo, capacidad) values ('RX-7', 54);
insert into tren (modelo, capacidad) values ('Suburban 1500', 55);
insert into tren (modelo, capacidad) values ('Grand Caravan', 56);
insert into tren (modelo, capacidad) values ('LTD Crown Victoria', 57);
insert into tren (modelo, capacidad) values ('Ram 3500', 58);
insert into tren (modelo, capacidad) values ('Talon', 59);
insert into tren (modelo, capacidad) values ('Monte Carlo', 60);
insert into tren (modelo, capacidad) values ('S80', 61);
insert into tren (modelo, capacidad) values ('Corvette', 62);
insert into tren (modelo, capacidad) values ('900', 63);
insert into tren (modelo, capacidad) values ('911', 64);
insert into tren (modelo, capacidad) values ('Mustang', 65);
insert into tren (modelo, capacidad) values ('F-Series', 66);
insert into tren (modelo, capacidad) values ('X6 M', 67);
insert into tren (modelo, capacidad) values ('Econoline E250', 68);
insert into tren (modelo, capacidad) values ('Exige', 69);
insert into tren (modelo, capacidad) values ('Continental GT', 70);
insert into tren (modelo, capacidad) values ('Ram 1500 Club', 71);
insert into tren (modelo, capacidad) values ('Corvette', 72);
insert into tren (modelo, capacidad) values ('Yukon XL 1500', 73);
insert into tren (modelo, capacidad) values ('Reliant', 74);
insert into tren (modelo, capacidad) values ('Truck', 75);
insert into tren (modelo, capacidad) values ('Bronco', 76);
insert into tren (modelo, capacidad) values ('Passat', 77);
insert into tren (modelo, capacidad) values ('Solara', 78);
insert into tren (modelo, capacidad) values ('Precis', 79);
insert into tren (modelo, capacidad) values ('DeVille', 80);
insert into tren (modelo, capacidad) values ('Blazer', 81);
insert into tren (modelo, capacidad) values ('RX-7', 82);
insert into tren (modelo, capacidad) values ('GTI', 83);
insert into tren (modelo, capacidad) values ('Quest', 84);
insert into tren (modelo, capacidad) values ('Civic Si', 85);
insert into tren (modelo, capacidad) values ('Fox', 86);
insert into tren (modelo, capacidad) values ('Acadia', 87);
insert into tren (modelo, capacidad) values ('Quattro', 88);
insert into tren (modelo, capacidad) values ('Town Car', 89);
insert into tren (modelo, capacidad) values ('Camaro', 90);
insert into tren (modelo, capacidad) values ('Camry Hybrid', 91);
insert into tren (modelo, capacidad) values ('Flex', 92);
insert into tren (modelo, capacidad) values ('Acadia', 93);
insert into tren (modelo, capacidad) values ('Stratus', 94);
insert into tren (modelo, capacidad) values ('Ascender', 95);
insert into tren (modelo, capacidad) values ('Trooper', 96);
insert into tren (modelo, capacidad) values ('Challenger', 97);
insert into tren (modelo, capacidad) values ('Golf', 98);
insert into tren (modelo, capacidad) values ('Monza', 99);
insert into tren (modelo, capacidad) values ('GX', 100);
